[package]
name = "bittravel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-tungstenite = { version = "*", features = ["native-tls"] }
tungstenite = { version = "0.27.0" }
spacetimedb-sdk = "1.0"
hex = "0.4"
tokio = "1.46.0"
futures-util = "0.3.31"
futures-channel = "0.3.31"
